@file:Suppress("SameParameterValue", "AssignedValueIsNeverRead")

package org.autojs.autojs.ksp

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import java.io.BufferedReader

class VersionCodesProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return VersionCodesProcessor(environment)
    }
}

class VersionCodesProcessor(private val env: SymbolProcessorEnvironment) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val rows = readFromResource("version-codes.csv")
        if (rows.isEmpty()) return emptyList()

        val sorted = rows.sortedByDescending { it.apiLevel.toIntOrNull() ?: Int.MIN_VALUE }

        val pkg = "org.autojs.autojs.runtime.api.augment.util"
        val fileName = "VersionCodesInfoGenerated"
        val fileExtension = "kt"
        val content = buildString {
            appendLine("// Generated by KSP. DO NOT EDIT.")
            appendLine("@file:Suppress(\"unused\",\"MemberVisibilityCanBePrivate\",\"RedundantVisibilityModifier\")")
            appendLine("package $pkg")
            appendLine()
            appendLine("import org.autojs.autojs.runtime.api.augment.util.VersionCodes")
            appendLine("import org.autojs.autojs.util.RhinoUtils.newNativeObject")
            appendLine("import org.mozilla.javascript.ScriptableObject.PERMANENT")
            appendLine("import org.mozilla.javascript.ScriptableObject.READONLY")
            appendLine()
            appendLine("internal object $fileName {")
            appendLine("  @JvmField")
            appendLine("  val list: List<VersionCodes.Info> = listOf(")
            sorted.forEachIndexed { idx, r ->
                val comma = if (idx < sorted.lastIndex) "," else ""
                appendLine(
                    "    VersionCodes.Info(${q(r.versionCode)}, ${q(r.releaseName)}, ${q(r.internalCodename)}, ${q(r.platformVersion)}, ${q(r.apiLevel)}, ${q(r.releaseDate)})$comma"
                )
            }
            appendLine("  )")
            appendLine()
            appendLine("  @JvmField")
            appendLine("  val obj = newNativeObject().apply {")
            sorted.forEach { r ->
                appendLine("    run {")
                appendLine("      val info = VersionCodes.Info(${q(r.versionCode)}, ${q(r.releaseName)}, ${q(r.internalCodename)}, ${q(r.platformVersion)}, ${q(r.apiLevel)}, ${q(r.releaseDate)})")
                appendLine("      defineProperty(${q(r.versionCode)}, { info.toNativeObject() }, null, READONLY or PERMANENT)")
                appendLine("    }")
            }
            appendLine("  }")
            appendLine("}")
        }
        val bytes = content.toByteArray()
        try {
            resolver.getNewFiles().find {
                it.fileName == "${fileName}.${fileExtension}" && it.packageName.asString() == pkg
            } ?: env.codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = false),
                packageName = pkg,
                fileName = fileName,
                extensionName = fileExtension,
            ).use { it.write(bytes) }
        } catch (_: FileAlreadyExistsException) {
            // Already written in the same/previous round, skip directly.
            // zh-CN: 已被同一/前一轮写入, 直接跳过.
        }
        return emptyList()
    }

    data class Row(
        val versionCode: String,
        val releaseName: String,
        val internalCodename: String,
        val platformVersion: String,
        val apiLevel: String,
        val releaseDate: String,
    )

    private fun readFromResource(name: String): List<Row> {
        val url = javaClass.classLoader.getResource(name) ?: throw RuntimeException("Resource not found: $name")
        return url.openStream().bufferedReader().use { br -> parseCsv(br) }
    }

    private fun parseCsv(br: BufferedReader): List<Row> {
        val rows = mutableListOf<Row>()
        var isHeader = true
        br.forEachLine { raw ->
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) return@forEachLine
            if (isHeader) {
                isHeader = false; return@forEachLine
            }
            val cells = splitCsv(line)
            if (cells.size < 6) throw RuntimeException("Invalid line: $raw")
            rows += Row(
                versionCode = cells[0],
                releaseName = cells[1],
                internalCodename = cells[2],
                platformVersion = cells[3],
                apiLevel = cells[4],
                releaseDate = cells[5],
            )
        }
        return rows
    }

    // Simple CSV implementation with minimal quote handling.
    // zh-CN: 简单 CSV, 此处实现了最小引号处理.
    private fun splitCsv(line: String): List<String> {
        val out = mutableListOf<String>()
        val sb = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val c = line[i]
            when {
                c == '"' -> {
                    if (inQuotes && i + 1 < line.length && line[i + 1] == '"') {
                        sb.append('"'); i++
                    } else {
                        inQuotes = !inQuotes
                    }
                }
                c == ',' && !inQuotes -> {
                    out += sb.toString(); sb.setLength(0)
                }
                else -> sb.append(c)
            }
            i++
        }
        out += sb.toString()
        return out.map { it.trim().removeSurrounding("\"") }
    }

    private fun q(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

}
